Repository WiIIiam278/HuskHomes, pull requests merged in 2021-07, with the labels that each got.

#62 Add /tpignore command
  pom.xml
  src/main/java/me/william278/huskhomes2/HuskHomes.java
  src/main/java/me/william278/huskhomes2/commands/TpAcceptCommand.java
  src/main/java/me/william278/huskhomes2/commands/TpIgnoreCommand.java
  src/main/java/me/william278/huskhomes2/data/DataManager.java
  src/main/java/me/william278/huskhomes2/data/SQL/MySQL.java
  src/main/java/me/william278/huskhomes2/data/SQL/SQLite.java
  src/main/java/me/william278/huskhomes2/listeners/PlayerListener.java
  src/main/java/me/william278/huskhomes2/listeners/PluginMessageListener.java
  src/main/java/me/william278/huskhomes2/migrators/UpgradeDatabase.java
  src/main/java/me/william278/huskhomes2/teleport/TeleportRequestHandler.java
  src/main/resources/Languages/en-gb.yml
  src/main/resources/Languages/it-it.yml
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: status: in progress

#65 Add /tpoffline
  src/main/java/me/william278/huskhomes2/HuskHomes.java
  src/main/java/me/william278/huskhomes2/MessageManager.java
  src/main/java/me/william278/huskhomes2/commands/TpIgnoreCommand.java
  src/main/java/me/william278/huskhomes2/commands/TpOfflineCommand.java
  src/main/java/me/william278/huskhomes2/data/DataManager.java
  src/main/java/me/william278/huskhomes2/data/SQL/MySQL.java
  src/main/java/me/william278/huskhomes2/data/SQL/SQLite.java
  src/main/java/me/william278/huskhomes2/listeners/PlayerListener.java
  src/main/java/me/william278/huskhomes2/migrators/UpgradeDatabase.java
  src/main/java/me/william278/huskhomes2/teleport/TeleportManager.java
  src/main/resources/Languages/en-gb.yml
  src/main/resources/Languages/it-it.yml
  src/main/resources/plugin.yml
Labels: status: in progress, type: feature request

#73 New simplified Chinese support
  src/main/resources/Languages/zh-cn.yml
Labels: type: localisation
