Repository WiIIiam278/HuskHomes, pull requests merged in 2022-08, with the labels that each got.

#198 Update it-it.yml
  common/src/main/resources/locales/it-it.yml
Labels: type: localisation

#200 Refactor #getServer() to be pre-cached from a CachedServer yaml file
  bukkit/src/main/java/net/william278/huskhomes/BukkitHuskHomes.java
  bukkit/src/main/java/net/william278/huskhomes/api/HuskHomesAPI.java
  bukkit/src/main/java/net/william278/huskhomes/listener/BukkitEventListener.java
  bukkit/src/main/java/net/william278/huskhomes/player/BukkitPlayer.java
  common/src/main/java/net/william278/huskhomes/HuskHomes.java
  common/src/main/java/net/william278/huskhomes/command/SpawnCommand.java
  common/src/main/java/net/william278/huskhomes/command/TpCommand.java
  common/src/main/java/net/william278/huskhomes/config/CachedServer.java
  common/src/main/java/net/william278/huskhomes/config/CachedSpawn.java
  common/src/main/java/net/william278/huskhomes/listener/EventListener.java
  common/src/main/java/net/william278/huskhomes/teleport/TeleportManager.java
Labels: type: bug, type: feature request

#201 Upload dev builds to GH Actions as an artifact
  .github/workflows/java_ci.yml
Labels: status: in progress
